// prettier-ignore
module.exports = [
  { id: 'Brave_0_60_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.60, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_0_61_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.61, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_0_63_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.63, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_0_65_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.65, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_0_67_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.67, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_0_68_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.68, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_0_69_OSX_Catalina', expected: { browser: 'Brave',         browserVersion: 0.69, layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_1_OSX_Catalina',    expected: { browser: 'Brave',         browserVersion: 1,    layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_1_1_OSX_Catalina',  expected: { browser: 'Brave',         browserVersion: 1.1,  layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Brave_1_3_OSX_Catalina',  expected: { browser: 'Brave',         browserVersion: 1.3,  layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_41_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 41,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_42_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 42,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_43_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 43,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_45_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 45,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_46_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 46,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_47_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 47,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_48_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 48,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_49_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 49,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_50_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 50,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_51_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 51,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_52_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 52,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_53_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 53,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_54_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 54,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_55_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 55,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_56_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 56,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_57_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 57,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_58_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 58,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_59_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 59,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_60_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 60,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_61_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 61,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_62_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 62,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_63_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 63,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_64_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 64,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_65_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 65,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_66_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 66,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_67_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 67,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_68_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 68,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_69_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 69,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_70_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 70,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_71_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 71,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_72_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 72,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_74_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 74,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_75_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 75,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_76_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 76,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_77_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 77,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_78_Linux_x86_64',  expected: { browser: 'Chrome',        browserVersion: 78,   layout: 'Blink',    layoutVersion: undefined, os: 'Linux',   osVersion: undefined } },
  { id: 'Chrome_79_Windows_10',    expected: { browser: 'Chrome',        browserVersion: 79,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Chrome_80_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Chrome_80_Windows_10',    expected: { browser: 'Chrome',        browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Chrome_81_OSX_Catalina',  expected: { browser: 'Chrome',        browserVersion: 81,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Edge_40_Windows_10',      expected: { browser: 'Edge',          browserVersion: 40,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Edge_41_Windows_10',      expected: { browser: 'Edge',          browserVersion: 41,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Edge_42_Windows_10',      expected: { browser: 'Edge',          browserVersion: 42,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Edge_44_Windows_10',      expected: { browser: 'Edge',          browserVersion: 44,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Edge_79_OSX_Catalina',    expected: { browser: 'Edge',          browserVersion: 79,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Edge_80_OSX_Catalina',    expected: { browser: 'Edge',          browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Edge_80_Windows_10',      expected: { browser: 'Edge',          browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_42_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 42,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_43_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 43,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_44_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 44,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_45_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 45,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_46_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 46,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_47_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 47,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_48_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 48,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_49_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 49,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_50_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 50,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_51_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 51,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_52_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 52,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_53_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 53,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_54_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 54,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_55_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 55,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_56_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 56,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_57_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 57,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_58_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 58,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_59_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 59,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_60_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 60,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_61_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 61,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_62_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 62,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_63_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 63,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_64_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 64,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_65_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_66_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 66,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_67_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 67,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_68_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 68,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_69_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 69,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_70_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 70,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_71_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 71,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_72_Linux_x86_64', expected: { browser: 'Firefox',       browserVersion: 72,   layout: 'Gecko',    layoutVersion: undefined, os: 'Linux',   osVersion: undefined } },
  { id: 'Firefox_72_OSX_Catalina', expected: { browser: 'Firefox',       browserVersion: 72,   layout: 'Gecko',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Firefox_72_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 72,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_73_Windows_10',   expected: { browser: 'Firefox',       browserVersion: 73,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Firefox_73_Linux_x86_64', expected: { browser: 'Firefox',       browserVersion: 73,   layout: 'Gecko',    layoutVersion: undefined, os: 'Linux',   osVersion: undefined } },
  { id: 'IE_11_Windows_10',        expected: { browser: 'IE',            browserVersion: 11,   layout: 'Trident',  layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Opera_37_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 37,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_38_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 38,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_39_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 39,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_40_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 40,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_41_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 41,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_42_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 42,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_43_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 43,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_44_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 44,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_45_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 45,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_46_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 46,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_47_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 47,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_48_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 48,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_49_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 49,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_50_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 50,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_51_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 51,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_52_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 52,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_53_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 53,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_54_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 54,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_55_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 55,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_56_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 56,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_57_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 57,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_58_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 58,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_60_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 60,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_60_Windows_10',     expected: { browser: 'Opera',         browserVersion: 60,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Opera_62_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 62,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_62_Windows_10',     expected: { browser: 'Opera',         browserVersion: 62,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Opera_63_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 63,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_63_Windows_10',     expected: { browser: 'Opera',         browserVersion: 63,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: undefined } },
  { id: 'Opera_64_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 64,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_65_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 65,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Opera_66_OSX_Catalina',   expected: { browser: 'Opera',         browserVersion: 66,   layout: 'Blink',    layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Safari_13_OSX_Catalina',  expected: { browser: 'Safari',        browserVersion: 13,   layout: 'WebKit',   layoutVersion: undefined, os: 'OS X',    osVersion: undefined } },
  { id: 'Safari_13_iOS',           expected: { browser: 'Safari',        browserVersion: 13,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: undefined } }
];
