// prettier-ignore
module.exports = [
  { id: 'Brave_0_60_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.60, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_0_61_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.61, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_0_63_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.63, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_0_65_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.65, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_0_67_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.67, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_0_68_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.68, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_0_69_OSX_Catalina',   expected: { browser: 'Brave',   browserVersion: 0.69, layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_1_OSX_Catalina',      expected: { browser: 'Brave',   browserVersion: 1,    layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_1_1_OSX_Catalina',    expected: { browser: 'Brave',   browserVersion: 1.1,  layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Brave_1_3_OSX_Catalina',    expected: { browser: 'Brave',   browserVersion: 1.3,  layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_41_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 41,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_42_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 42,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_43_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 43,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_45_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 45,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_46_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 46,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_47_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 47,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_48_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 48,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_49_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 49,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_50_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 50,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_51_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 51,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_52_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 52,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_53_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 53,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_54_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 54,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_55_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 55,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_58_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 58,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_59_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 59,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_60_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 60,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_61_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 61,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_62_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 62,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_63_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 63,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_64_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 64,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_65_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 65,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_66_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 66,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_67_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 67,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_68_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 68,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_69_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 69,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_70_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 70,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_71_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 71,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_72_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 72,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_74_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 74,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_75_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 75,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_76_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 76,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_77_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 77,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_78_Linux_x86_64',    expected: { browser: 'Chrome',  browserVersion: 78,   layout: 'Blink',    layoutVersion: undefined, os: 'Linux',   osVersion: undefined } },
  { id: 'Chrome_79_Windows_10',      expected: { browser: 'Chrome',  browserVersion: 79,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Chrome_80_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Chrome_80_Windows_10',      expected: { browser: 'Chrome',  browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Chrome_81_OSX_Catalina',    expected: { browser: 'Chrome',  browserVersion: 81,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Edge_40_Windows_10',        expected: { browser: 'Edge',    browserVersion: 40,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Edge_41_Windows_10',        expected: { browser: 'Edge',    browserVersion: 41,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Edge_42_Windows_10',        expected: { browser: 'Edge',    browserVersion: 42,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Edge_44_Windows_10',        expected: { browser: 'Edge',    browserVersion: 44,   layout: 'EdgeHTML', layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Edge_79_OSX_Catalina',      expected: { browser: 'Edge',    browserVersion: 79,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Edge_80_OSX_Catalina',      expected: { browser: 'Edge',    browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Edge_80_Windows_10',        expected: { browser: 'Edge',    browserVersion: 80,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_42_Windows_10',     expected: { browser: 'Firefox', browserVersion: 42,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_43_Windows_10',     expected: { browser: 'Firefox', browserVersion: 43,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_44_Windows_10',     expected: { browser: 'Firefox', browserVersion: 44,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_45_Windows_10',     expected: { browser: 'Firefox', browserVersion: 45,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_46_Windows_10',     expected: { browser: 'Firefox', browserVersion: 46,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_46_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 46,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_47_Windows_10',     expected: { browser: 'Firefox', browserVersion: 47,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_47_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 47,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_48_Windows_10',     expected: { browser: 'Firefox', browserVersion: 48,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_48_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 48,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_49_Windows_10',     expected: { browser: 'Firefox', browserVersion: 49,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_49_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 49,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_50_Windows_10',     expected: { browser: 'Firefox', browserVersion: 50,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_50_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 50,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_51_Windows_10',     expected: { browser: 'Firefox', browserVersion: 51,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_51_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 51,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_52_Windows_10',     expected: { browser: 'Firefox', browserVersion: 52,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_52_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 52,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_53_Windows_10',     expected: { browser: 'Firefox', browserVersion: 53,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_53_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 53,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_54_Windows_10',     expected: { browser: 'Firefox', browserVersion: 54,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_54_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 54,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_55_Windows_10',     expected: { browser: 'Firefox', browserVersion: 55,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_55_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 55,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_56_Windows_10',     expected: { browser: 'Firefox', browserVersion: 56,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_56_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 56,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_57_Windows_10',     expected: { browser: 'Firefox', browserVersion: 57,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_57_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 57,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_58_Windows_10',     expected: { browser: 'Firefox', browserVersion: 58,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_58_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 58,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_59_Windows_10',     expected: { browser: 'Firefox', browserVersion: 59,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_59_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 59,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_60_Windows_10',     expected: { browser: 'Firefox', browserVersion: 60,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_60_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 60,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_61_Windows_10',     expected: { browser: 'Firefox', browserVersion: 61,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_61_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 61,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_62_Windows_10',     expected: { browser: 'Firefox', browserVersion: 62,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_62_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 62,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_63_Windows_10',     expected: { browser: 'Firefox', browserVersion: 63,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_63_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 63,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_64_Windows_10',     expected: { browser: 'Firefox', browserVersion: 64,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_64_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 64,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_65_Windows_10',     expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_65_Android_4_4',    expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.4       } },
  { id: 'Firefox_65_Android_5',      expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 5         } },
  { id: 'Firefox_65_Android_6',      expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 6         } },
  { id: 'Firefox_65_Android_7_1',    expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 7.1       } },
  { id: 'Firefox_65_Android_8',      expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 8         } },
  { id: 'Firefox_65_Android_8_1',    expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 8.1       } },
  { id: 'Firefox_65_Android_9',      expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 9         } },
  { id: 'Firefox_65_Android_10',     expected: { browser: 'Firefox', browserVersion: 65,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 10        } },
  { id: 'Firefox_66_Windows_10',     expected: { browser: 'Firefox', browserVersion: 66,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_66_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 66,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_67_Windows_10',     expected: { browser: 'Firefox', browserVersion: 67,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_67_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 67,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_68_Windows_10',     expected: { browser: 'Firefox', browserVersion: 68,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_68_Android_4_3',    expected: { browser: 'Firefox', browserVersion: 68,   layout: 'Gecko',    layoutVersion: undefined, os: 'Android', osVersion: 4.3       } },
  { id: 'Firefox_69_Windows_10',     expected: { browser: 'Firefox', browserVersion: 69,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_70_Windows_10',     expected: { browser: 'Firefox', browserVersion: 70,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_71_Windows_10',     expected: { browser: 'Firefox', browserVersion: 71,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_72_Linux_x86_64',   expected: { browser: 'Firefox', browserVersion: 72,   layout: 'Gecko',    layoutVersion: undefined, os: 'Linux',   osVersion: undefined } },
  { id: 'Firefox_72_OSX_Catalina',   expected: { browser: 'Firefox', browserVersion: 72,   layout: 'Gecko',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Firefox_72_Windows_10',     expected: { browser: 'Firefox', browserVersion: 72,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_73_Windows_10',     expected: { browser: 'Firefox', browserVersion: 73,   layout: 'Gecko',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Firefox_73_Linux_x86_64',   expected: { browser: 'Firefox', browserVersion: 73,   layout: 'Gecko',    layoutVersion: undefined, os: 'Linux',   osVersion: undefined } },
  { id: 'IE_11_Windows_10',          expected: { browser: 'IE',      browserVersion: 11,   layout: 'Trident',  layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Opera_37_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 37,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_38_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 38,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_39_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 39,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_40_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 40,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_41_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 41,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_42_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 42,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_43_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 43,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_44_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 44,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_45_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 45,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_46_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 46,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_47_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 47,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_48_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 48,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_49_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 49,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_50_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 50,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_51_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 51,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_52_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 52,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_53_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 53,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_54_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 54,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_55_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 55,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_56_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 56,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_57_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 57,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_58_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 58,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_60_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 60,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_60_Windows_10',       expected: { browser: 'Opera',   browserVersion: 60,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Opera_62_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 62,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_62_Windows_10',       expected: { browser: 'Opera',   browserVersion: 62,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Opera_63_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 63,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_63_Windows_10',       expected: { browser: 'Opera',   browserVersion: 63,   layout: 'Blink',    layoutVersion: undefined, os: 'Windows', osVersion: 10        } },
  { id: 'Opera_64_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 64,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_65_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 65,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Opera_66_OSX_Catalina',     expected: { browser: 'Opera',   browserVersion: 66,   layout: 'Blink',    layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Safari_8_OSX_Yosemite',     expected: { browser: 'Safari',  browserVersion: 8,    layout: 'WebKit',   layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.10     } },
  { id: 'Safari_8_iOS_8_1',          expected: { browser: 'Safari',  browserVersion: 8,    layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 8.1       } },
  { id: 'Safari_9_OSX_El_Capitan',   expected: { browser: 'Safari',  browserVersion: 9,    layout: 'WebKit',   layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.11     } },
  { id: 'Safari_9_iOS_9',            expected: { browser: 'Safari',  browserVersion: 9,    layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 9         } },
  { id: 'Safari_10_OSX_Sierra',      expected: { browser: 'Safari',  browserVersion: 10,   layout: 'WebKit',   layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.12     } },
  { id: 'Safari_10_iOS_10_3',        expected: { browser: 'Safari',  browserVersion: 10,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 10.3      } },
  { id: 'Safari_11_OSX_High_Sierra', expected: { browser: 'Safari',  browserVersion: 11,   layout: 'WebKit',   layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.13     } },
  { id: 'Safari_11_iOS_11_2',        expected: { browser: 'Safari',  browserVersion: 11,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 11.2      } },
  { id: 'Safari_11_iOS_11_3',        expected: { browser: 'Safari',  browserVersion: 11,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 11.3      } },
  { id: 'Safari_11_iOS_11_4',        expected: { browser: 'Safari',  browserVersion: 11,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 11.4      } },
  { id: 'Safari_12_iOS_12_1',        expected: { browser: 'Safari',  browserVersion: 12,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 12.1      } },
  { id: 'Safari_12_OSX_Mojave',      expected: { browser: 'Safari',  browserVersion: 12,   layout: 'WebKit',   layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.14     } },
  { id: 'Safari_12_iOS_12_2',        expected: { browser: 'Safari',  browserVersion: 12,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 12.2      } },
  { id: 'Safari_12_iOS_12_3',        expected: { browser: 'Safari',  browserVersion: 12,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 12.3      } },
  { id: 'Safari_13_OSX_Catalina',    expected: { browser: 'Safari',  browserVersion: 13,   layout: 'WebKit',   layoutVersion: undefined, os: 'Mac OS',  osVersion: 10.15     } },
  { id: 'Safari_13_iOS_13_2',        expected: { browser: 'Safari',  browserVersion: 13,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 13.2      } },
  { id: 'Safari_13_iOS_13_3',        expected: { browser: 'Safari',  browserVersion: 13,   layout: 'WebKit',   layoutVersion: undefined, os: 'iOS',     osVersion: 13.3      } }
];
